# DATA601 Homework Assignment 6
Due Date: Sunday, December 5, 23:50 PM

In [ ]:
import re

#### Q1
Write a regexp that will find all the Data Science courses mentioned in the following sentence. <br>
<code> sentence1 = 'So far, I took DATA 601, DATA 604, and DATA 605. Next semester I will take DATA 602.'</code> <br>
such that the output will look like <br>
<code> ['DATA 601', 'DATA 604', 'DATA 605', 'DATA 602'] </code>

In [ ]:
sentence1 = 'So far, I took DATA 601, DATA 604, and DATA 605. Next semester I will take DATA 602.'
# Answer
y = re.findall('DATA\s\d{3}', sentence1) 
print(y)


['DATA 601', 'DATA 604', 'DATA 605', 'DATA 602']


### Q2
Write a regexp that will find all the Data Science courses mentioned in the following sentence. <br>
<code> sentence2 = 'So far, I took DATA601, DATA-604, and DATA 605. Next semester I will take DATA602.'</code><br>
such that the output will look like <br>
<code> ['DATA601', 'DATA-604', 'DATA 605', 'DATA602'] </code>

In [ ]:
sentence2 = 'So far, I took DATA601, DATA-604, and DATA 605. Next semester I will take DATA602.'
# Answer
y = re.findall('DATA.\d{1,}', sentence2) #d{2,} also works
print(y)

['DATA601', 'DATA-604', 'DATA 605', 'DATA602']


### Q3
Write a regexp that will find all the graduate courses mentioned in the following sentence. <br>
<code> sentence3 = 'So far, I took DATA 601, ENMG 652, and DATA 605. Next semester I will take DATA 602.'</code><br>
such that the output will look like <br>
<code> ['DATA 601', 'ENMG 652', 'DATA 605', 'DATA 602'] </code>

In [ ]:
sentence3 = 'So far, I took DATA 601, ENMG 652, and DATA 605. Next semester I will take DATA 602.'
# Answer
y = re.findall('DATA.\d{1,}|ENMG....', sentence3) 
print(y)


['DATA 601', 'ENMG 652', 'DATA 605', 'DATA 602']


#### Q4
Write a regexp that will match any Python Notebook (.ipynb) file in the following list. <br>
<code> Files = ['lecture1.ipynb','lecture2.ipynb','lecture3.doc','lecture4.py','solutions.ipynb'] </code> <br>
and print the list, e.g. your output will look like <br>
<code>['lecture1.ipynb', 'lecture2.ipynb', 'solutions.ipynb']</code>

In [ ]:
Files = ['lecture1.ipynb','lecture2.ipynb','lecture3.doc','lecture4.py','solutions.ipynb']
# Answer
#convert Files into one string
mylist = ""
for e in Files:
    e = str(e) + " "
    mylist += e
  
print(mylist) #print this string
y = re.findall("\S{2,}.ipynb", mylist) #2 or more non-whitespace chars 
print(y)


lecture1.ipynb lecture2.ipynb lecture3.doc lecture4.py solutions.ipynb 
['lecture1.ipynb', 'lecture2.ipynb', 'solutions.ipynb']


#### Q5
Create a regexp which detects Microsoft Word file names (either *.doc or *.docx) which contain at a numeral, and print their names for the following list <br>
<code>Files2 = ['hw1.docx','hw2.docx','hw3.py','hw_last.docx','hw5.doc'] </code>

In [ ]:
Files2 = ['hw1.docx','hw2.docx','hw3.py','hw_last.docx','hw5.doc']
# Answer
#'\d{1, }do[c|x]'

#convert Files into one string
mylist = ""
for e in Files2:
    e = str(e) + " "
    mylist += e
  
print(mylist) #print this string
y = re.findall('(\S{2,}\d{1,}.docx|\S{2,}\d{1,}.doc)', mylist) #|\S{2,}\d{1,}doc DATA.\d{1,}|ENMG....
print(y)

hw1.docx hw2.docx hw3.py hw_last.docx hw5.doc 
['hw1.docx', 'hw2.docx', 'hw5.doc']


### Q6. 
Compile a pattern that matches with web-addresses in the following sentence. <br> 
<code> sentence = 'Google\'s address is www.google.com.' </code>

In [ ]:
sentence = 'Google\'s address is www.google.com.'
# Answer
pattern = re.compile(r'www.\S{1,}')
## search for a match
mo = pattern.search(sentence)
mo.group()

'www.google.com.'

### Q7
Extract all the words in the following sentence <br>
<code>sentence = 'OMG! There is a punctuation. I want to remove it?'</code> <br>
The output should look like this <br>
<code> ['OMG', 'There', 'is', 'a', 'punctuation', 'I', 'want', 'to', 'remove', 'it'] </code>

In [ ]:
sentence = 'OMG! There is a punctuation. I want to remove it?'
words_pattern = '[a-z]+'
re.findall(words_pattern, sentence, flags=re.IGNORECASE)

['OMG', 'There', 'is', 'a', 'punctuation', 'I', 'want', 'to', 'remove', 'it']

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=4511c9db-3ff3-4de2-bdfe-cb0da3a697d3' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>